name: E2E Tests with Screenshots

on:
  schedule:
    # Run daily at 2 AM UTC
    - cron: "0 2 * * *"
  workflow_dispatch: # Allow manual triggering

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Build application
        run: npm run build

      - name: Run Playwright tests
        run: npx playwright test

      - name: Commit and push forecast images
        if: always()
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

          # Create forecast images directory if it doesn't exist
          mkdir -p src/assets/forecast-images/

          # Force add forecast images (override .gitignore)
          git add --force src/assets/forecast-images/

          # Check if there are any changes to commit
          if ! git diff --staged --quiet; then
            git commit -m "Update weather forecast images - $(date '+%Y-%m-%d %H:%M:%S')"
            git push
          else
            echo "No forecast image changes to commit"
          fi
